name: Build Flutter Linux ARM64 on GitHub Actions

on:
  push:
    branches: [main]  # 可自定义分支
  workflow_dispatch:

jobs:
  build-linux-arm64:
    name: Build on ARM64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run on ARM64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ secrets.GITHUB_TOKEN }}

          install: |
            apt update
            apt install -y clang cmake ninja-build pkg-config libgtk-3-dev curl git unzip xz-utils
            git clone https://github.com/flutter/flutter.git -b stable /flutter
            echo 'export PATH=/flutter/bin:$PATH' >> ~/.bashrc

          run: |
            export PATH=/flutter/bin:$PATH
            flutter doctor -v
            flutter config --enable-linux-desktop
            flutter pub get
            flutter build linux

            cd build/linux/arm64/release
            zip -r creo_touch_x-linux-arm64.zip bundle

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: creo_touch_x-linux-arm64
          path: build/linux/arm64/release/creo_touch_x-linux-arm64.zip