name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  build-linux:
    # If you want to run the same action on x86 and ARM, you can use a matrix strategy
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.29.3
      - run: flutter --version
      - name: Install dependencies from Apt
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y;
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - name: Install Flutter
        run: flutter doctor
      
