name: build-linux-arm64

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  build-linux:
    # If you want to run the same action on x86 and ARM, you can use a matrix strategy
    strategy:
      matrix:
        os: [ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml 
      - run: flutter --version

      
      - name: Install dependencies from Apt
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y;
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - name: Install Flutter
        run: flutter doctor
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Flutter project
        run: flutter build linux --verbose --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: creo_touch_x-linux-arm64
          path: ${{ github.workspace }}/build/linux/arm64/release/bundle