name: Build and deploy Flutter app for Linux arm64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 设置 Flutter 环境，指定 Flutter 版本
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'  # 指定明确的 Flutter 版本

    # 安装 zip 工具
    - name: Install zip
      run: sudo apt-get install -y zip

    # 安装依赖包
    - name: Install dependencies
      run: flutter pub get

    # 构建 Linux arm64 版本的 Flutter 应用
    - name: Build Flutter app for Linux arm64
      run: flutter build linux --release --target-platform=linux-arm64

    # 在 ARM 架构上运行构建命令
    - name: Run on ARM architecture
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: arm64
        run: |
          echo "Running on ARM architecture"
          flutter build linux --release --target-platform=linux-arm64

    # 打包构建结果（zip 文件）
    - name: Package build output
      run: zip -r build_output.zip build/linux/arm64/release/bundle

    # 上传构建结果到 GitHub Release（可选）
    - name: Upload build output to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build_output.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}