name: Build Flutter for Linux ARM64

on:
  push:
    branches: [main] # 你也可以改为其他分支

jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev unzip

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter for Linux ARM64
        run: flutter build linux --target-platform=linux-arm64

      - name: Package build output
        run: |
          cd build/linux/arm64/release
          zip -r creo_touch_x-linux-arm64.zip bundle

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: creo_touch_x-linux-arm64
          path: build/linux/arm64/release/creo_touch_x-linux-arm64.zip